# ベースイメージの指定
FROM mysql:8.0.36

# COPY ./my.cnf /etc/mysql/conf.d/
COPY ./giu.txt /etc/mysql/
COPY ./pass20.txt /etc/mysql/
COPY ./ex15.txt /etc/mysql/
COPY ./Brit.txt /etc/mysql/
COPY ./shuraba.txt /etc/mysql/
COPY ./toefl700.txt /etc/mysql/
COPY ./create_table.sql /etc/mysql/